### ISSUE TITLE
aliceui 网站不可访问

### ISSUE THREAD

**Issue by Xaber20110202** [aliceui/aliceui.github.io#71]
目前我们公司使用了aliceUI的开源代码，但是这块如果网站停止维护，能否提供一个demo集合页，不然我们公司前端的一些日常的工作，就受到了一些阻碍。谢谢！

**Comment by WenJimmy** [comment]
域名都到期了~看来应该没人维护了

**Comment by Xaber20110202** [comment]
通过spm doc 生成了不完善的版本，勉强可以看api。不过内部决定自己写一份最简单的css ui，实现商家端功能。

**Comment by monsterooo** [comment]
维护部维护，能否给一个消息？网站打开不

**Comment by Xaber20110202** [comment]
https://github.com/aliceui/box
https://github.com/aliceui/button-dropdown
https://github.com/aliceui/button
https://github.com/aliceui/base
https://github.com/aliceui/tipbox
https://github.com/aliceui/step
.......

git clone 上面这些alice的模块


https://github.com/spmjs/spm-doc
npm install spm-doc -g  安装spm-doc

进入这些目录，通过
spm-doc build
生成文档

cd ~/Desktop/aliceui/tiptext && spm-doc build && cd ../aliceui/tiptext && spm-doc build && 
............

**Comment by sehuo** [comment]
spm的源是停止维护了，源码还可以从github上clone
